name: Lint and Build

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@vulpee'
      # - name: Setup NPM
      #   run: echo "@vulpee:registry=https://npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH }}" > ~/.npmrc
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH}}
      - name: Lint
        run: npm run lint

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@vulpee'
      # - name: Setup NPM
      #   run: echo "@vulpee:registry=https://npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH }}" > ~/.npmrc
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH}}
      - name: Build
        run: npm run build
